#Continue-setting for llama-server
name: Local Config
version: 1.0.0
schema: v1
models:
  - name: deepseek-coder-v2-lite-instruct_Q4_K_M.gguf
    provider: llama.cpp
    model: deepseek-coder-v2-lite-instruct_Q4_K_M.gguf
    apiBase: "http://localhost:8080"
    systemMessage: "あなたは優秀なエンジニアです。思考（thinkタグ）は自由な言語で行って構いませんが、最終的な回答と解説は必ず日本語で出力してください。"
    roles:
      - chat
      - edit
      - apply
      - autocomplete
  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text-v1.5-GGUF:Q6_K
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
  